name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
      - '.github/ISSUE_TEMPLATE'
      - '.github/CODE_OF_CONDUCT.md'
      - '.github/CONTRIBUTING.md'
      - '.github/pull_request_template.md'
      - '.github/SECURITY.md'
      - '.github/SUPPORT.md'
      - '.github/CompatHelper.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
      - '.github/ISSUE_TEMPLATE'
      - '.github/CODE_OF_CONDUCT.md'
      - '.github/CONTRIBUTING.md'
      - '.github/pull_request_template.md'
      - '.github/SECURITY.md'
      - '.github/SUPPORT.md'
      - '.github/CompatHelper.yml'
  release:
    types:
      - created

jobs:
  ci:
    services:
      postgres:
        image: postgres:13.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.5']
        julia-arch: [x64]
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Cache artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts 
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v0.1
      - uses: julia-actions/julia-runtest@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PGHOST: localhost
          POSTGIS_PORT: ${{ job.services.postgres.ports[5432] }}
          PGDATABASE: postgres
          PGUSER: postgres
          PGPASSWORD: postgres
          GH_PAT: ${{ secrets.GH_PAT }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
      - uses: julia-actions/julia-docdeploy@releases/v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
